/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBareV3SplatRouteImport } from './routes/api/public/bare.v3.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBareV3SplatRoute = ApiPublicBareV3SplatRouteImport.update({
  id: '/api/public/bare/v3/$',
  path: '/api/public/bare/v3/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/bare/v3/$': typeof ApiPublicBareV3SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/bare/v3/$': typeof ApiPublicBareV3SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/bare/v3/$': typeof ApiPublicBareV3SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/bare/v3/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/bare/v3/$'
  id: '__root__' | '/' | '/api/public/bare/v3/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicBareV3SplatRoute: typeof ApiPublicBareV3SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bare/v3/$': {
      id: '/api/public/bare/v3/$'
      path: '/api/public/bare/v3/$'
      fullPath: '/api/public/bare/v3/$'
      preLoaderRoute: typeof ApiPublicBareV3SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicBareV3SplatRoute: ApiPublicBareV3SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
